# Purpose: Creates the container for running the aqmsDutyReviewBackend software
#          in a Ubuntu container.
# Usage: podman build -t aqmsdutyreviewbackender:latest -f Dockerfile.u26
#        buildah bud -t aqmsdutyreviewbackender:latest -f Dockerfile.u26
FROM ubuntu:26.04
COPY @PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz .
LABEL version="@PROJECT_VERSION@"
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get autoclean -y &&\
    apt-get -y install bash &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    tar -xf ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz &&\
    mv ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/bin/aqmsDutyReviewBackend /usr/local/bin &&\
    rm -r ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/ &&\
    rm -r /var/lib/apt/lists/* ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz

#CMD /usr/local/bin/aqmsDutyReviewBackend --config=config.ini
