--- Purpose: Defines every table and function in the database: the
--- frontend users, their public keys, and the event store.  Everything
--- is in the default 'public' schema.
---
--- The backend connects as a postgres role (aqmsdb_writer /
--- aqmsdb_reader); rows in 'users' are application users, not postgres
--- roles.  The two are unrelated.
---
--- Copyright: Ben Baker (UUSS) distributed under the MIT license.

--------------------------------------------------------------------------
---                               Users                                 ---
--------------------------------------------------------------------------

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    --- Stable numeric identifier; other tables should FK to this.
    user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    --- The user name - e.g., jsmith (stored lowercase).
    name TEXT UNIQUE NOT NULL
        CHECK (name = lower(name) AND length(name) > 0),
    --- The hashed password.  This is generated by something like
    --- libsodium's crypto_pwhash_str.  Plaintext never enters the db.
    password_hash TEXT NOT NULL CHECK (length(password_hash) > 0),
    --- What this user may do.  With one database per system (test,
    --- prod) there is nothing left for a permission to range over, so
    --- it is a column here rather than a join table.
    ---
    --- These are ranked, not independent: admin implies read_write
    --- implies read_only.  See user_has_permission below, which is the
    --- one place that ordering is written down.  Adding a level means
    --- editing this CHECK and that function together.
    permission TEXT NOT NULL DEFAULT 'read_only'
        CHECK (permission IN ('read_only', 'read_write', 'admin')),
    --- The provisioning deadline for an account issued with a dummy
    --- password.  NULL means an ordinary, activated account.  Non-NULL
    --- means the account still has the password it was handed and will
    --- be deleted after this instant if that has not changed.
    ---
    --- This exists because password_updated cannot answer the question:
    --- it is set on creation as well as on change, so 'never changed
    --- it' and 'changed it immediately' look identical.  Set by
    --- add_provisional_user, cleared by update_user_password -- so
    --- changing the password IS the activation, with no second step to
    --- forget.
    provisional_until TIMESTAMPTZ DEFAULT NULL,
    --- When the user was created.
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- The last time the password was updated.
    password_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- Last login, by password or by key.  NULL = never.
    last_login TIMESTAMPTZ DEFAULT NULL
);

--- Adds a user.  Returns TRUE on success; FALSE if the name or password
--- hash is empty, the permission is not a known level, or the user
--- already exists.
---
--- Ungated: it takes no actor and checks nothing.  It is granted to no
--- role, so only a superuser can call it directly -- that is the
--- bootstrap path for the first administrator, and the reason the
--- chicken-and-egg problem has an answer.  Everything else goes through
--- admin_add_user.
CREATE OR REPLACE FUNCTION add_user(p_name TEXT, p_password_hash TEXT,
                                    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    INSERT INTO users (name, password_hash, permission)
        VALUES (lower(trim(p_name)), p_password_hash,
                lower(trim(p_permission)));
    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RETURN FALSE;
    --- An unknown permission level trips the CHECK; report it the same
    --- way as any other bad input rather than raising to the backend.
    WHEN check_violation THEN
        RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- Fetches the stored hash for verification with something like
--- libsodium's crypto_pwhash_str_verify.  Returns NULL if no such user.
---
--- A provisional account whose deadline has passed is treated as
--- already gone, even though the sweep has not run yet.  Otherwise the
--- dummy password stays usable for however long the interval is between
--- sweeps, and the deletion schedule silently becomes the real deadline.
CREATE OR REPLACE FUNCTION get_password_hash(p_name TEXT)
RETURNS TEXT AS $$
    SELECT password_hash
      FROM users
     WHERE name = lower(trim(p_name))
       AND (provisional_until IS NULL OR provisional_until > NOW());
$$ LANGUAGE sql;

--- Records a successful login.  Returns TRUE if the user was found.
--- The backend should call this after crypto_pwhash_str_verify succeeds.
CREATE OR REPLACE FUNCTION record_login(p_name TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE users
       SET last_login = NOW()
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Removes a user.  Returns TRUE if a row was deleted.  The user's keys
--- cascade away with them.  Ungated and granted to no role; the backend
--- calls admin_remove_user.
CREATE OR REPLACE FUNCTION remove_user(p_name TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_deleted INTEGER;
BEGIN
    DELETE FROM users
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_deleted = ROW_COUNT;
    RETURN n_deleted > 0;
END;
$$ LANGUAGE plpgsql;

--- Updates a user's password.  Returns TRUE if the user was found and
--- the (non-empty) hash was set.
---
--- Clearing provisional_until here is what activates a provisioned
--- account: setting your own password is the only evidence anyone
--- wanted, so it is not a separate call the frontend could skip.
--- An account already past its deadline is refused rather than
--- activated -- the sweep has simply not caught it yet.
CREATE OR REPLACE FUNCTION update_user_password(p_name TEXT,
                                                p_password_hash TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    UPDATE users
       SET password_hash = p_password_hash,
           password_updated = NOW(),
           provisional_until = NULL
     WHERE name = lower(trim(p_name))
       AND (provisional_until IS NULL OR provisional_until > NOW());
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Sets a user's permission level.  Returns FALSE if the user does not
--- exist or the level is not a known one.  Ungated and granted to no
--- role; the backend calls admin_set_user_permission.
CREATE OR REPLACE FUNCTION set_user_permission(p_name TEXT, p_permission TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE users
       SET permission = lower(trim(p_permission))
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
EXCEPTION WHEN check_violation THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- What can this user do?  Returns the permission name, or NULL if
--- there is no such user.  The backend consults this on every
--- authorization check.
CREATE OR REPLACE FUNCTION get_user_permission(p_name TEXT)
RETURNS TEXT AS $$
    SELECT permission
      FROM users
     WHERE name = lower(trim(p_name));
$$ LANGUAGE sql;

--- Does this user hold AT LEAST the named level?  The levels are
--- ranked, so an admin passes a read_write check without anyone having
--- to remember to write 'permission IN (...)' at every call site --
--- which is how an admin ends up mysteriously unable to write data.
---
--- Returns FALSE for an unknown user and for an unknown level, so a
--- typo'd requirement denies rather than admits.
CREATE OR REPLACE FUNCTION user_has_permission(p_name TEXT, p_required TEXT)
RETURNS BOOLEAN AS $$
    SELECT COALESCE(
        (SELECT CASE u.permission WHEN 'read_only'  THEN 1
                                  WHEN 'read_write' THEN 2
                                  WHEN 'admin'      THEN 3 END
           FROM users u WHERE u.name = lower(trim(p_name)))
        >=
        CASE lower(trim(p_required)) WHEN 'read_only'  THEN 1
                                     WHEN 'read_write' THEN 2
                                     WHEN 'admin'      THEN 3 END,
        FALSE);
$$ LANGUAGE sql;

--------------------------------------------------------------------------
---                          Administration                             ---
--------------------------------------------------------------------------
--- Everything below takes p_actor: the logged-in user on whose behalf
--- the backend is acting.  The check happens here rather than in the
--- backend for the same reason password hashes are unreachable there --
--- the database should not depend on the backend being correct.
---
--- Authorization failure RAISEs insufficient_privilege (SQLSTATE 42501)
--- instead of returning FALSE.  A boolean cannot distinguish 'you may
--- not' from 'that did not work', and those are a 403 and a 400 to the
--- frontend.  Bad input still returns FALSE, as everywhere else.

--- Raises unless p_actor is an activated administrator.  Granted to no
--- role: it is called from inside the definer functions below, which
--- run as the owner and so do not need EXECUTE of their own.
---
--- A provisional admin is refused.  They hold a password that was
--- e-mailed to them and have proved nothing yet; that is not who should
--- be able to create accounts.
CREATE OR REPLACE FUNCTION require_admin(p_actor TEXT)
RETURNS VOID AS $$
DECLARE v_permission TEXT;
        v_provisional TIMESTAMPTZ;
BEGIN
    SELECT permission, provisional_until
      INTO v_permission, v_provisional
      FROM users WHERE name = lower(trim(p_actor));
    --- One message for every failure: whether a given name exists is
    --- not something an unauthorized caller should be able to probe.
    IF v_permission IS NULL
       OR v_permission <> 'admin'
       OR v_provisional IS NOT NULL THEN
        RAISE EXCEPTION 'not authorized: administrator privilege required'
              USING ERRCODE = 'insufficient_privilege';
    END IF;
END;
$$ LANGUAGE plpgsql;

--- TRUE if this user is an activated administrator.  The frontend uses
--- it to decide whether to show the user-management page at all; the
--- functions below do not trust that decision.
CREATE OR REPLACE FUNCTION user_is_admin(p_name TEXT)
RETURNS BOOLEAN AS $$
    SELECT COALESCE(
        (SELECT permission = 'admin' AND provisional_until IS NULL
           FROM users WHERE name = lower(trim(p_name))),
        FALSE);
$$ LANGUAGE sql;

--- How many administrators can actually administer right now.
--- Provisional ones are excluded because require_admin refuses them:
--- counting them would let the last usable admin be removed on the
--- strength of one who cannot log in.
---
--- Takes no locks, so the answer is already stale by the time a caller
--- reads it.  Fine for showing a number; NOT the basis for deciding
--- whether an administrator may be removed - see
--- forbid_last_admin_removal, which counts under FOR UPDATE.
CREATE OR REPLACE FUNCTION count_active_admins()
RETURNS INTEGER AS $$
    SELECT count(*)::INTEGER FROM users
     WHERE permission = 'admin' AND provisional_until IS NULL;
$$ LANGUAGE sql;

--- Raises if p_name is the last activated administrator.  Called before
--- anything that would demote, delete, or de-activate one.
---
--- Without this the database can be locked out of its own user
--- management with a single ordinary-looking call, and the only way
--- back in is a superuser session.
---
--- The FOR UPDATE is the whole point of this function, and it is not
--- decoration.  Counting first and deleting second is safe only if
--- nothing else removes an administrator in between, and two
--- administrators on two browsers are exactly that: each counts two,
--- each deletes a different one, both commit, nobody is left.  That is
--- write skew, and it is the one anomaly snapshot isolation does NOT
--- rule out - REPEATABLE READ permits it just as READ COMMITTED does.
--- Measured on 18.4, both leave zero administrators.
---
--- Locking every activated administrator row, rather than only the one
--- being removed, is what makes the two conflict: the second caller
--- blocks on a row the first one holds even though it is removing a
--- different person, and when it wakes it re-reads and sees the count
--- it was going to be told about.  It then refuses, at the default
--- READ COMMITTED, with no retry loop anywhere.
---
--- SERIALIZABLE also closes it, and was rejected: the isolation level
--- cannot be set from inside a function - it has to be the first
--- statement of the transaction - so it would have to be imposed by
--- every caller, and it reports the conflict as a serialization failure
--- at COMMIT, which the backend would then have to recognise and
--- replay.  A lock the function takes for itself cannot be forgotten by
--- a caller.
---
--- ORDER BY name so that concurrent callers take the row locks in one
--- order and cannot deadlock against each other.
CREATE OR REPLACE FUNCTION forbid_last_admin_removal(p_name TEXT)
RETURNS VOID AS $$
DECLARE
    n_admins INTEGER;
BEGIN
    --- Nothing to protect if the target is not an activated admin, and
    --- no reason to take locks on their behalf.
    IF NOT user_is_admin(p_name) THEN
        RETURN;
    END IF;
    --- Deliberately not count_active_admins(): that one takes no locks,
    --- which is what makes it safe to call for display and unsafe to
    --- decide on.
    SELECT count(*) INTO n_admins
      FROM (SELECT 1 FROM users
             WHERE permission = 'admin' AND provisional_until IS NULL
             ORDER BY name
               FOR UPDATE) locked_admins;
    IF n_admins <= 1 THEN
        RAISE EXCEPTION 'refusing to leave the database with no administrator'
              USING ERRCODE = 'insufficient_privilege';
    END IF;
END;
$$ LANGUAGE plpgsql;

--- Creates a user directly, with a password the administrator chose.
--- Prefer admin_add_provisional_user: it does not require an
--- administrator to handle someone else's password at all.
CREATE OR REPLACE FUNCTION admin_add_user(
    p_actor TEXT, p_name TEXT, p_password_hash TEXT,
    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    PERFORM require_admin(p_actor);
    RETURN add_user(p_name, p_password_hash, p_permission);
END;
$$ LANGUAGE plpgsql;

--- The normal way to hire someone: create the account with a dummy
--- password valid for p_valid_for, hand it over out of band, and let it
--- delete itself if they never turn up.
CREATE OR REPLACE FUNCTION admin_add_provisional_user(
    p_actor TEXT, p_name TEXT, p_password_hash TEXT, p_valid_for INTERVAL,
    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    PERFORM require_admin(p_actor);
    RETURN add_provisional_user(p_name, p_password_hash, p_valid_for,
                                p_permission);
END;
$$ LANGUAGE plpgsql;

--- Changes someone's level -- the 'training is over, give them
--- read_write' call, and its reverse.
CREATE OR REPLACE FUNCTION admin_set_user_permission(
    p_actor TEXT, p_name TEXT, p_permission TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    PERFORM require_admin(p_actor);
    --- Demoting the last admin is the same lockout as deleting them.
    --- This also stops an administrator demoting themselves by
    --- accident, which is the likelier version.
    IF lower(trim(p_permission)) IS DISTINCT FROM 'admin' THEN
        PERFORM forbid_last_admin_removal(p_name);
    END IF;
    RETURN set_user_permission(p_name, p_permission);
END;
$$ LANGUAGE plpgsql;

--- Resets a forgotten password.  The new password is provisional, so
--- the user must replace it on their next login: an administrator who
--- resets an account should not be left holding a working credential
--- for it, and this way the window is p_valid_for rather than forever.
---
--- Returns FALSE if the user does not exist or the inputs are bad.
CREATE OR REPLACE FUNCTION admin_reset_user_password(
    p_actor TEXT, p_name TEXT, p_password_hash TEXT, p_valid_for INTERVAL)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    PERFORM require_admin(p_actor);
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_valid_for IS NULL OR p_valid_for <= INTERVAL '0' THEN
        RETURN FALSE;
    END IF;
    --- A reset makes the target provisional, and a provisional admin
    --- cannot act -- so resetting the last administrator, including
    --- yourself, is a lockout like any other.
    PERFORM forbid_last_admin_removal(p_name);
    UPDATE users
       SET password_hash = p_password_hash,
           password_updated = NOW(),
           provisional_until = NOW() + p_valid_for
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Deletes a user.  Their keys go with them.
CREATE OR REPLACE FUNCTION admin_remove_user(p_actor TEXT, p_name TEXT)
RETURNS BOOLEAN AS $$
BEGIN
    PERFORM require_admin(p_actor);
    PERFORM forbid_last_admin_removal(p_name);
    RETURN remove_user(p_name);
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------
---                        Provisioning users                           ---
--------------------------------------------------------------------------
--- With ~15 users there is no registration workflow.  An administrator
--- creates the account with a dummy password, hands that password to
--- the person out of band, and the account deletes itself if they never
--- turn it into a real one.
---
--- The dummy password is a real credential for as long as it lives, so
--- the script should generate a distinct random one per user and hash
--- it the same way any other password is hashed.  A shared, guessable
--- 'changeme' is the failure mode this design is otherwise vulnerable
--- to: an account nobody is watching, with a password everybody knows.

--- Creates a user holding a dummy password, valid for p_valid_for.
--- Returns TRUE on success; FALSE on empty input or an existing user.
--- Ungated and granted to no role; the backend calls
--- admin_add_provisional_user.
---
--- The interval is an argument, not a default written here, because the
--- .sql files deliberately carry no site policy -- the calling script
--- owns 'how long do they get', the same way create.sh owns the names.
CREATE OR REPLACE FUNCTION add_provisional_user(
    p_name TEXT, p_password_hash TEXT, p_valid_for INTERVAL,
    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_valid_for IS NULL OR p_valid_for <= INTERVAL '0' THEN
        RETURN FALSE;
    END IF;
    INSERT INTO users (name, password_hash, permission, provisional_until)
        VALUES (lower(trim(p_name)), p_password_hash,
                lower(trim(p_permission)), NOW() + p_valid_for);
    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RETURN FALSE;
    WHEN check_violation THEN
        RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- TRUE if this account is still holding the password it was issued.
--- The backend should call this after verifying a login and, when it
--- comes back TRUE, allow nothing but the password change: the person
--- on the other end has proved only that they received the dummy
--- password, which may have travelled by e-mail.
CREATE OR REPLACE FUNCTION user_must_change_password(p_name TEXT)
RETURNS BOOLEAN AS $$
    SELECT provisional_until IS NOT NULL
      FROM users
     WHERE name = lower(trim(p_name));
$$ LANGUAGE sql;

--- Deletes every provisional account whose deadline has passed, and
--- returns how many went.  Activated accounts have a NULL deadline and
--- are never candidates, so this cannot delete a real user however
--- often it runs.  Keys cascade with the user.
---
--- Call it on a timer -- cron, a systemd timer, or pg_cron if that
--- extension is installed:
---     psql -d aqmsdb_prod -c 'SELECT delete_expired_provisional_users();'
--- The exact schedule is not load-bearing: an expired account cannot
--- log in whether or not the sweep has reached it yet.
CREATE OR REPLACE FUNCTION delete_expired_provisional_users()
RETURNS INTEGER AS $$
DECLARE n_deleted INTEGER;
BEGIN
    DELETE FROM users
     WHERE provisional_until IS NOT NULL
       AND provisional_until <= NOW();
    GET DIAGNOSTICS n_deleted = ROW_COUNT;
    RETURN n_deleted;
END;
$$ LANGUAGE plpgsql;

--- Every user and their state.  Note the absence of password_hash:
--- this is shaped to be safe to hand straight to a frontend, and the
--- one column that must never go there is simply not selectable.
--- provisional_until is included so an operator can see who is pending
--- and how long they have left.
---
--- The timestamps come out as TEXT in RFC 3339, UTC, whole seconds:
---
---     2026-09-02T20:43:26Z
---
--- rather than as TIMESTAMPTZ.  A TIMESTAMPTZ is rendered by the
--- SESSION - DateStyle picks the shape and TimeZone picks the offset -
--- so the same instant leaves this function as
--- '2026-09-02 14:43:26.753472-06' in Utah in September, '...-07' in
--- January, and something else entirely on a server set to DateStyle
--- SQL.  The wire format of an API should not be a server setting.
---
--- The exact spelling matters to the browser.  Javascript's Date parses
--- the space-separated Postgres form only by falling into its lenient
--- non-standard path; the same string with a 'T' is REJECTED, because
--- that makes it look like ECMAScript's specified format, which demands
--- a two-part '+HH:MM' offset that Postgres' '-06' is not.  'Z' is in
--- the strict grammar and needs no offset at all.
---
--- Whole seconds because nothing here is timed that finely, and because
--- Date truncates to milliseconds regardless.  The columns keep their
--- microseconds; only this projection drops them.
---
--- to_char(NULL, ...) is NULL, so provisional_until and last_login stay
--- absent rather than becoming the string 'NULL'.
---
--- The DROP is required, not tidiness: this function used to return
--- TIMESTAMPTZ, and CREATE OR REPLACE cannot change a return type.
--- Dropping it also drops its SECURITY DEFINER setting and its GRANT,
--- which grantPrivileges.sql re-applies on the next create.sh run.
DROP FUNCTION IF EXISTS list_users();
CREATE OR REPLACE FUNCTION list_users()
RETURNS TABLE(name TEXT, permission TEXT, provisional_until TEXT,
              created TEXT, password_updated TEXT,
              last_login TEXT) AS $$
    SELECT u.name, u.permission,
           to_char(u.provisional_until AT TIME ZONE 'UTC',
                   'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           to_char(u.created AT TIME ZONE 'UTC',
                   'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           to_char(u.password_updated AT TIME ZONE 'UTC',
                   'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
           to_char(u.last_login AT TIME ZONE 'UTC',
                   'YYYY-MM-DD"T"HH24:MI:SS"Z"')
      FROM users u
     ORDER BY u.name;
$$ LANGUAGE sql;
