--- Purpose: Defines every table and function in the database: the
--- frontend users, their public keys, and the event store.  Everything
--- is in the default 'public' schema.
---
--- The backend connects as a postgres role (aqmsdb_writer /
--- aqmsdb_reader); rows in 'users' are application users, not postgres
--- roles.  The two are unrelated.
---
--- Copyright: Ben Baker (UUSS) distributed under the MIT license.

--------------------------------------------------------------------------
---                               Users                                 ---
--------------------------------------------------------------------------

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    --- Stable numeric identifier; other tables should FK to this.
    user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    --- The user name - e.g., jsmith (stored lowercase).
    name TEXT UNIQUE NOT NULL
        CHECK (name = lower(name) AND length(name) > 0),
    --- The hashed password.  This is generated by something like
    --- libsodium's crypto_pwhash_str.  Plaintext never enters the db.
    password_hash TEXT NOT NULL CHECK (length(password_hash) > 0),
    --- What this user may do.  With one database per system (test,
    --- prod) there is nothing left for a permission to range over, so
    --- it is a column here rather than a join table.  Adding a level
    --- (e.g., 'management') means editing this CHECK.
    permission TEXT NOT NULL DEFAULT 'read_only'
        CHECK (permission IN ('read_only', 'read_write')),
    --- The provisioning deadline for an account issued with a dummy
    --- password.  NULL means an ordinary, activated account.  Non-NULL
    --- means the account still has the password it was handed and will
    --- be deleted after this instant if that has not changed.
    ---
    --- This exists because password_updated cannot answer the question:
    --- it is set on creation as well as on change, so 'never changed
    --- it' and 'changed it immediately' look identical.  Set by
    --- add_provisional_user, cleared by update_user_password -- so
    --- changing the password IS the activation, with no second step to
    --- forget.
    provisional_until TIMESTAMPTZ DEFAULT NULL,
    --- When the user was created.
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- The last time the password was updated.
    password_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- Last login, by password or by key.  NULL = never.
    last_login TIMESTAMPTZ DEFAULT NULL
);

--- Adds a user.  Returns TRUE on success; FALSE if the name or password
--- hash is empty, the permission is not a known level, or the user
--- already exists.
CREATE OR REPLACE FUNCTION add_user(p_name TEXT, p_password_hash TEXT,
                                    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    INSERT INTO users (name, password_hash, permission)
        VALUES (lower(trim(p_name)), p_password_hash,
                lower(trim(p_permission)));
    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RETURN FALSE;
    --- An unknown permission level trips the CHECK; report it the same
    --- way as any other bad input rather than raising to the backend.
    WHEN check_violation THEN
        RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- Fetches the stored hash for verification with something like
--- libsodium's crypto_pwhash_str_verify.  Returns NULL if no such user.
---
--- A provisional account whose deadline has passed is treated as
--- already gone, even though the sweep has not run yet.  Otherwise the
--- dummy password stays usable for however long the interval is between
--- sweeps, and the deletion schedule silently becomes the real deadline.
CREATE OR REPLACE FUNCTION get_password_hash(p_name TEXT)
RETURNS TEXT AS $$
    SELECT password_hash
      FROM users
     WHERE name = lower(trim(p_name))
       AND (provisional_until IS NULL OR provisional_until > NOW());
$$ LANGUAGE sql;

--- Records a successful login.  Returns TRUE if the user was found.
--- The backend should call this after crypto_pwhash_str_verify succeeds.
CREATE OR REPLACE FUNCTION record_login(p_name TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE users
       SET last_login = NOW()
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Removes a user.  Returns TRUE if a row was deleted.  The user's keys
--- cascade away with them.
CREATE OR REPLACE FUNCTION remove_user(p_name TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_deleted INTEGER;
BEGIN
    DELETE FROM users
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_deleted = ROW_COUNT;
    RETURN n_deleted > 0;
END;
$$ LANGUAGE plpgsql;

--- Updates a user's password.  Returns TRUE if the user was found and
--- the (non-empty) hash was set.
---
--- Clearing provisional_until here is what activates a provisioned
--- account: setting your own password is the only evidence anyone
--- wanted, so it is not a separate call the frontend could skip.
--- An account already past its deadline is refused rather than
--- activated -- the sweep has simply not caught it yet.
CREATE OR REPLACE FUNCTION update_user_password(p_name TEXT,
                                                p_password_hash TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    UPDATE users
       SET password_hash = p_password_hash,
           password_updated = NOW(),
           provisional_until = NULL
     WHERE name = lower(trim(p_name))
       AND (provisional_until IS NULL OR provisional_until > NOW());
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Sets a user's permission level.  Returns FALSE if the user does not
--- exist or the level is not a known one.
CREATE OR REPLACE FUNCTION set_user_permission(p_name TEXT, p_permission TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE users
       SET permission = lower(trim(p_permission))
     WHERE name = lower(trim(p_name));
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
EXCEPTION WHEN check_violation THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- What can this user do?  Returns the permission name, or NULL if
--- there is no such user.  The backend consults this on every
--- authorization check.
CREATE OR REPLACE FUNCTION get_user_permission(p_name TEXT)
RETURNS TEXT AS $$
    SELECT permission
      FROM users
     WHERE name = lower(trim(p_name));
$$ LANGUAGE sql;

--------------------------------------------------------------------------
---                        Provisioning users                           ---
--------------------------------------------------------------------------
--- With ~15 users there is no registration workflow.  An operator's
--- script creates the account with a dummy password, hands that
--- password to the person out of band, and the account deletes itself
--- if they never turn it into a real one.
---
--- The dummy password is a real credential for as long as it lives, so
--- the script should generate a distinct random one per user and hash
--- it the same way any other password is hashed.  A shared, guessable
--- 'changeme' is the failure mode this design is otherwise vulnerable
--- to: an account nobody is watching, with a password everybody knows.

--- Creates a user holding a dummy password, valid for p_valid_for.
--- Returns TRUE on success; FALSE on empty input or an existing user.
---
--- The interval is an argument, not a default written here, because the
--- .sql files deliberately carry no site policy -- the calling script
--- owns 'how long do they get', the same way create.sh owns the names.
CREATE OR REPLACE FUNCTION add_provisional_user(
    p_name TEXT, p_password_hash TEXT, p_valid_for INTERVAL,
    p_permission TEXT DEFAULT 'read_only')
RETURNS BOOLEAN AS $$
BEGIN
    IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_password_hash IS NULL OR length(p_password_hash) = 0 THEN
        RETURN FALSE;
    END IF;
    IF p_valid_for IS NULL OR p_valid_for <= INTERVAL '0' THEN
        RETURN FALSE;
    END IF;
    INSERT INTO users (name, password_hash, permission, provisional_until)
        VALUES (lower(trim(p_name)), p_password_hash,
                lower(trim(p_permission)), NOW() + p_valid_for);
    RETURN TRUE;
EXCEPTION
    WHEN unique_violation THEN
        RETURN FALSE;
    WHEN check_violation THEN
        RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- TRUE if this account is still holding the password it was issued.
--- The backend should call this after verifying a login and, when it
--- comes back TRUE, allow nothing but the password change: the person
--- on the other end has proved only that they received the dummy
--- password, which may have travelled by e-mail.
CREATE OR REPLACE FUNCTION user_must_change_password(p_name TEXT)
RETURNS BOOLEAN AS $$
    SELECT provisional_until IS NOT NULL
      FROM users
     WHERE name = lower(trim(p_name));
$$ LANGUAGE sql;

--- Deletes every provisional account whose deadline has passed, and
--- returns how many went.  Activated accounts have a NULL deadline and
--- are never candidates, so this cannot delete a real user however
--- often it runs.  Keys cascade with the user.
---
--- Call it on a timer -- cron, a systemd timer, or pg_cron if that
--- extension is installed:
---     psql -d aqmsdb_prod -c 'SELECT delete_expired_provisional_users();'
--- The exact schedule is not load-bearing: an expired account cannot
--- log in whether or not the sweep has reached it yet.
CREATE OR REPLACE FUNCTION delete_expired_provisional_users()
RETURNS INTEGER AS $$
DECLARE n_deleted INTEGER;
BEGIN
    DELETE FROM users
     WHERE provisional_until IS NOT NULL
       AND provisional_until <= NOW();
    GET DIAGNOSTICS n_deleted = ROW_COUNT;
    RETURN n_deleted;
END;
$$ LANGUAGE plpgsql;

--- Every user and their state.  Note the absence of password_hash:
--- this is shaped to be safe to hand straight to a frontend, and the
--- one column that must never go there is simply not selectable.
--- provisional_until is included so an operator can see who is pending
--- and how long they have left.
CREATE OR REPLACE FUNCTION list_users()
RETURNS TABLE(name TEXT, permission TEXT, provisional_until TIMESTAMPTZ,
              created TIMESTAMPTZ, password_updated TIMESTAMPTZ,
              last_login TIMESTAMPTZ) AS $$
    SELECT u.name, u.permission, u.provisional_until, u.created,
           u.password_updated, u.last_login
      FROM users u
     ORDER BY u.name;
$$ LANGUAGE sql;

--------------------------------------------------------------------------
---                          User public keys                           ---
--------------------------------------------------------------------------
--- PUBLIC keys only -- the private half never leaves the user's client.
--- Users register keys for programmatic/API access (a la SSH
--- authorized_keys); the backend verifies signatures with something
--- like libsodium's crypto_sign_verify_detached.
--- Keys are revoked, never deleted: the row is the audit trail of what
--- could authenticate when.  (Deleting the user still cascades.)

DROP TABLE IF EXISTS user_keys CASCADE;
CREATE TABLE user_keys(
    key_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL
        REFERENCES users(user_id) ON DELETE CASCADE,
    --- User-facing label, e.g., 'laptop', 'ci-runner'.  Unique per
    --- user so 'revoke my laptop key' is unambiguous.
    key_name TEXT NOT NULL CHECK (length(key_name) > 0),
    --- The public key, e.g., base64 of libsodium crypto_sign_PUBLICKEYBYTES.
    --- Globally unique: one key must not identify two users.
    public_key TEXT UNIQUE NOT NULL CHECK (length(public_key) > 0),
    --- Recorded so a future algorithm migration is data, not archaeology.
    algorithm TEXT NOT NULL DEFAULT 'ed25519'
        CHECK (algorithm = lower(algorithm)),
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- NULL = no expiry.
    expires TIMESTAMPTZ DEFAULT NULL,
    --- NULL = active.  Set once; never unset.
    revoked TIMESTAMPTZ DEFAULT NULL,
    last_used TIMESTAMPTZ DEFAULT NULL,
    UNIQUE (user_id, key_name)
);
CREATE INDEX user_keys_user_id_idx ON user_keys(user_id);

--- Registers a public key for a user.  Returns TRUE on success; FALSE
--- if the user doesn't exist, inputs are empty, the key name is taken
--- for this user, or the public key is already registered (to anyone).
CREATE OR REPLACE FUNCTION add_user_key(
    p_name TEXT, p_key_name TEXT, p_public_key TEXT,
    p_algorithm TEXT DEFAULT 'ed25519', p_expires TIMESTAMPTZ DEFAULT NULL)
RETURNS BOOLEAN AS $$
DECLARE v_user_id BIGINT;
BEGIN
    IF p_key_name IS NULL OR length(trim(p_key_name)) = 0 OR
       p_public_key IS NULL OR length(trim(p_public_key)) = 0 THEN
        RETURN FALSE;
    END IF;
    SELECT user_id INTO v_user_id
      FROM users WHERE name = lower(trim(p_name));
    IF v_user_id IS NULL THEN
        RETURN FALSE;
    END IF;
    INSERT INTO user_keys (user_id, key_name, public_key, algorithm, expires)
        VALUES (v_user_id, trim(p_key_name), trim(p_public_key),
                lower(trim(p_algorithm)), p_expires);
    RETURN TRUE;
EXCEPTION WHEN unique_violation THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

--- Revokes a key by (user, key name).  Returns TRUE if an active key
--- was revoked.  The row remains for audit.
CREATE OR REPLACE FUNCTION revoke_user_key(p_name TEXT, p_key_name TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE user_keys k
       SET revoked = NOW()
      FROM users u
     WHERE k.user_id = u.user_id
       AND u.name = lower(trim(p_name))
       AND k.key_name = trim(p_key_name)
       AND k.revoked IS NULL;
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- The authentication workhorse: given a presented public key, return
--- the owning user's name -- but only if the key is active (not
--- revoked, not expired).  Returns NULL otherwise; the backend then
--- verifies the request signature against this key and, on success,
--- calls record_key_use.
--- The same deadline check as get_password_hash: a provisional account
--- that registered a key must not keep authenticating with it past the
--- point where its password stopped working.
CREATE OR REPLACE FUNCTION get_user_by_key(p_public_key TEXT)
RETURNS TEXT AS $$
    SELECT u.name
      FROM user_keys k
      JOIN users u ON u.user_id = k.user_id
     WHERE k.public_key = trim(p_public_key)
       AND k.revoked IS NULL
       AND (k.expires IS NULL OR k.expires > NOW())
       AND (u.provisional_until IS NULL OR u.provisional_until > NOW());
$$ LANGUAGE sql;

--- Records a successful key authentication.  Also touches the user's
--- last_login so key-based and password-based access share one
--- 'when were they here last' answer.
CREATE OR REPLACE FUNCTION record_key_use(p_public_key TEXT)
RETURNS BOOLEAN AS $$
DECLARE n_updated INTEGER;
BEGIN
    UPDATE user_keys
       SET last_used = NOW()
     WHERE public_key = trim(p_public_key)
       AND revoked IS NULL;
    GET DIAGNOSTICS n_updated = ROW_COUNT;
    IF n_updated > 0 THEN
        UPDATE users u
           SET last_login = NOW()
          FROM user_keys k
         WHERE k.user_id = u.user_id
           AND k.public_key = trim(p_public_key);
    END IF;
    RETURN n_updated > 0;
END;
$$ LANGUAGE plpgsql;

--- Lists a user's keys and their states.  The frontend's 'manage my
--- keys' page is built from this.  Public keys are public, so every
--- column here is safe to hand to the client.
CREATE OR REPLACE FUNCTION list_user_keys(p_name TEXT)
RETURNS TABLE(key_name TEXT, algorithm TEXT, created TIMESTAMPTZ,
              expires TIMESTAMPTZ, revoked TIMESTAMPTZ,
              last_used TIMESTAMPTZ) AS $$
    SELECT k.key_name, k.algorithm, k.created, k.expires, k.revoked,
           k.last_used
      FROM user_keys k
      JOIN users u ON u.user_id = k.user_id
     WHERE u.name = lower(trim(p_name))
     ORDER BY k.created;
$$ LANGUAGE sql;

--------------------------------------------------------------------------
---                               Events                                ---
--------------------------------------------------------------------------
--- The event store.  Unlike the auth tables, this one is reached
--- directly: the backend roles hold table privileges on it and write
--- ordinary INSERT/UPDATE statements.  There is nothing to hide behind
--- a function the way there is with a password hash.

DROP TABLE IF EXISTS events CASCADE;
CREATE TABLE events(
    --- Supplied by the writer, not generated here: no identity column,
    --- no sequence.  The event already has an identity upstream and
    --- this table records it rather than inventing a second one.
    event_identifier BIGINT PRIMARY KEY,
    --- When the event first arrived.  Set once, on INSERT, and held
    --- there by the trigger below.
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    --- Maintained by the trigger below on every UPDATE, so it means
    --- 'when this row last changed' and not merely 'when it arrived'.
    last_update TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data JSONB NOT NULL
);

--- Supports 'what changed since I last polled', which is the query this
--- table exists to answer.  Drop it if nothing scans by time.
CREATE INDEX events_last_update_idx ON events(last_update);

--- Without this, last_update is really a second created timestamp: the
--- DEFAULT fires on INSERT and never again.  The trigger makes an
--- UPDATE that forgets to set it still tell the truth, and pins
--- created against an UPDATE that sets it by accident -- an upsert that
--- lists every column will otherwise overwrite it with the new row's
--- default.
CREATE OR REPLACE FUNCTION events_set_last_update()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_update = NOW();
    NEW.created = OLD.created;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER events_last_update_trigger
    BEFORE UPDATE ON events
    FOR EACH ROW
    EXECUTE FUNCTION events_set_last_update();
